name: datasci_barcode_scanning
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.0.20
  http: ^0.13.5
  image_picker: ^0.8.4+4
  google_fonts: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/GreenLogo.png
    - assets/images/GroceryItems.png
    - assets/images/RecipeGeneration.png
    - assets/images/Ingredients.png
    - assets/images/Recipe.png
