name: datasci_barcode_scanning
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.0.20
  http: ^1.2.2
  image_picker: ^1.1.2
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/GreenLogo.png
    - assets/images/GroceryItems.png
    - assets/images/AllergyDetection.png
    - assets/images/Ingredients.png
    - assets/images/logo.png
    - assets/images/Recipe.png
    - assets/images/RecipeGeneration.png
    - assets/images/agnese.png
    - assets/images/dhyuti.jpg
    - assets/images/phoebe.jpg
    - assets/images/rita.png
    - assets/images/Sean.png
    - assets/images/Subha.jpg
    - assets/images/Svein.JPG

